[package]
edition = "2024"
name = "hanzo-mcp-server"
version = { workspace = true }

[[bin]]
name = "hanzo-mcp-server"
path = "src/main.rs"

[lib]
name = "hanzo_mcp_server"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
agent-client-protocol = { version = "0.4.3", features = ["unstable"] }
hanzo-arg0 = { workspace = true }
hanzo-common = { workspace = true, features = ["cli"] }
hanzo-core = { workspace = true }
hanzo-protocol = { workspace = true }
hanzo-app-server-protocol = { workspace = true }
hanzo-utils-json-to-toml = { workspace = true }
hanzo-app-server = { workspace = true }
mcp-types = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
shlex = { workspace = true }
tokio = { workspace = true, features = [
    "io-std",
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
] }
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
uuid = { workspace = true, features = ["serde", "v7"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
