[package]
name = "hanzo-git-apply"
version = { workspace = true }
edition = "2024"

[lib]
name = "hanzo_git_apply"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
once_cell = { workspace = true }
regex = { workspace = true }
tempfile = { workspace = true }
