[package]
name = "hanzo-app-server-protocol"
version = { workspace = true }
edition = "2024"

[lints]
workspace = true

[dependencies]
hanzo-protocol = { workspace = true }
mcp-types = { workspace = true }
